### ISSUE TITLE
Style Cleanup For v1.0.0

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/ionic-app#170]
### Description

Clean up overall stylin of app, make consistent.

### Tasks
- [x] same button colors (see new colors in `colors.ts`)
- [x] surface/paper for stats overlay
- [x] Kwiz loading screen still has light blue color -> change to something greenish
