### ISSUE TITLE
Include @kwizapp/eslint-config files 

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/ionic-app#20]
### Description

Include config files from [@kwizzapp/eslint-config](https://github.com/kwizapp/eslint-config/packages) to configure `eslint` and `prettier`.

### Tasks

- [x] add `.npmrc` for GPR
- [x] replace current config with provided config files from the shared package
- [x] update workflow (tell docker build where to find package in GPR)

### Context 
https://github.com/kwizapp/eslint-config/issues/1
