### ISSUE TITLE
Track Score and Lives of Player client-side

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/ionic-app#30]
### Description

Introuce a library such as [zustand](https://github.com/react-spring/zustand) or the React Context API to store global information such as `score` and `lives`.

### Tasks

- [x] evaluate appropriate library
- [x] add global store
- [x] initialize start state in global store whenever the player starts a new game session
- [x] assure that the state is available after page transition

### Context 
[Story: Points Overlay](https://github.com/kwizapp/kwiz/issues/10)
