### ISSUE TITLE
Landing Screen

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/ionic-app#31]
### Description

Implement a landing screen that acts as a dedicated point of entry to the application.

### Tasks
- [x] replace ionic favicon etc.
- [x] add logo and name of application
- [x] add slogan
- [x] add a button that starts the game (redirect to [Blurred Poster Screen](https://github.com/kwizapp/kwiz/issues/9))
 
### Context 
[Story: Landing Screen](https://github.com/kwizapp/kwiz/issues/8)
