### ISSUE TITLE
Blurred Poster Screen

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/ionic-app#32]
### Description

Once the player starts the game, the player is redirected to the Blurred Poster Screen. Update the current implementation and make it use data from the backend.

### Tasks

- [x] retrieve poster dynamically from api with graphql query
- [x] make use of animation library for unblurring the poster (10 seconds) [react-spring](https://www.react-spring.io/) or [ionic animations](https://ionicframework.com/docs/utilities/animations)
- [x] redirect the player to the next screen ([Question Screen](https://github.com/kwizapp/kwiz/issues/11)) if the screen gets tapped
- [x] record the time it took the user until the screen was tapped

### Context 
[Story: Blurred Poster Screen](https://github.com/kwizapp/kwiz/issues/9)
