### ISSUE TITLE
Question Screen

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/ionic-app#33]
### Description

Once the player presses the blurred screen, he player needs to select the correct movie/series title out of 4 possible titles. Depending on the selected answer, the player is redirected to a success screen or a failure screen.

### Tasks

- [x] retrieve three additional movie/series titles that can be displayed as choose-able options
- [x] display the options as clickable cards
- [x] on click, a request should be sent to the api, which in turn validates the users selected guess
- [x] on sucess -> redirect to [Success Screen](https://github.com/kwizapp/kwiz/issues/12)
- [x] on failure -> redirect to [Failure Screen](https://github.com/kwizapp/kwiz/issues/13)

### Context 
[Story: Success Screen](https://github.com/kwizapp/kwiz/issues/12)
[Story: Failure Screen](https://github.com/kwizapp/kwiz/issues/13)
