### ISSUE TITLE
Success Screen (and Bonus Question redirect)

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/ionic-app#34]
### Description

Implement a Success Screen that is shown to the player if he/she gives the correct answer on the previous screen.

### Tasks

- [x] The screen shows the points that the player has earned by answering the previous question correctly.
- [x] The screen shows how many points the player now has in total.
- [x] The screen shows the increase of the points with an animation.
- [x] The screen shows two buttons (after the animation has finished!): one for playing it safe and one for "gambling", where the player can answer an additional question to double his points.
- [x] The "gambling" button is only available if the previous questions was a "blurred poster" question and not a "bonus question".
- [x] If the player clicks on the "continue" button, he is redirected to the [Trivia Screen](https://github.com/kwizapp/kwiz/issues/14).
- [x] If the player clicks on the "gambling" button, he is redirected to the [Bonus Question Screen](https://github.com/kwizapp/kwiz/issues/15).

### Context 
[Story: Success Screen](https://github.com/kwizapp/kwiz/issues/12)
