### ISSUE TITLE
Failure Screen

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/ionic-app#36]
### Description

Show a failure screen if the player gave the wrong guess for a question.

### Tasks

- [x] The screen shows my answer as well as the correct answer such that I can compare
- [x] The screen shows my new total score
- [x] The screen shows that I have lost a life if I have answered the "blurred poster question" incorrectly
- [x] The screen shows how many points I have lost if I have answered the "bonus question" incorrectly
- [x] The deduction of points is animated
- [x] After a delay, the player is redirected to the next screen (i.e., the [Trivia Screen](https://github.com/kwizapp/kwiz/issues/14))

### Context 
 [Story: Failure Screen](https://github.com/kwizapp/kwiz/issues/13)
