### ISSUE TITLE
Bonus Question Screen

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/ionic-app#37]
### Description

Add a bonus question screen with an interactive "puzzle" where the user can double his/her points if it's answered correctly. Should he/she get the answer wrong, then the player also loses the points he/she received in on the previous screen.

### Tasks

- [x] The screen displays clickable nodes. Each node has a corresponding movie/series poster attached.
- [x] The player needs to decide whether the already correctly guessed movie was released before, between or after the displayed movies.
- [x] If the player answers correctly, the [Success Screen](https://github.com/kwizapp/kwiz/issues/12) is shown and points are added (but no bonus question is possible from there).
- [x] If the player answers incorrectly, the [Failure Screen](https://github.com/kwizapp/kwiz/issues/13) is shown and points are deducted.

### Context 
[Story: Question Screen ("Bonus")](https://github.com/kwizapp/kwiz/issues/15)

### Additional Ideas
- Fruit-Ninja mode, where the player needs to slice up wrong facts of a move (the facts rain down on the screen)
