### ISSUE TITLE
Game Settings

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/ionic-app#40]
### Description

**Additions to this issue are welcome!**

Add the possibility for a player to adjust the settings for a game beforehand. This could include the following:
* number of rounds to be played
* difficulty
* genre of movies
* etc.

### Tasks

- [ ] The number of rounds to be played can be adjusted (to start a finite game).
- [ ] The number of rounds to be played is displayed.
- [ ] The desired level of difficulty can be adjusted.
- [ ] The desired type of movies to play with can be selected (by genre, time-span, or similar).
- [ ] The whole game adjusts to the selected parameters.

### Context 
[Story: Game Parameters](https://github.com/kwizapp/kwiz/issues/18)
